### ISSUE TITLE
Change Home page to be Group page

### ISSUE THREAD

**Issue by IsaiahSavage** [IsaiahSavage/mvnu-spiritual-life-app#19]
DRAFT:
Move home page content to separate Account page instead of swiping
Make group page the new home screen

**Comment by PiersenS** [comment]
As a user
When I log into the app
I should see the page that shows information about my group.

**Comment by IsaiahSavage** [comment]
Still need to reimplement the Profile page as a separate page

**Comment by IsaiahSavage** [comment]
> Still need to reimplement the Profile page as a separate page

See #6 : will be implemented as a part of this (larger) issue.
